name: publish
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run test # Test again to make sure no failing builds get published. Implicitly builds the package.
        env:
          TEST_TRIAS_URL: ${{ secrets.TEST_TRIAS_URL }}
          TEST_TRIAS_REF: ${{ secrets.TEST_TRIAS_REF }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
